name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: 12-ejercicio-cicd

jobs:

  # JOBS DEL FRONTEND


  frontend-lint: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Linter Frontend
        run: pnpm lint:frontend

  frontend-test: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Test Frontend
        run: pnpm test:frontend

  frontend-build:
    needs: [frontend-lint, frontend-test]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Build Frontend
        run: pnpm build:frontend


  # JOBS DEL BACKEND

  backend-lint: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Linter Backend
        run: pnpm lint:backend

  backend-test: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Test Backend
        run: pnpm test:backend

  backend-build:
    needs: [backend-lint, backend-test]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Build Backend
        run: pnpm build:backend